services:
  app:
    networks:
      - app-network
      - common-net

  # db:
  #   networks:
  #     common-net:
  #       aliases:
  #         - ip-management-db
  #         - db

networks:
  common-net:
    external: true
